# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HospitalId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.BigIntegerField(max_length=12)),
                ('Name', models.CharField(max_length=250)),
                ('HospitalId', models.TextField()),
            ],
        ),
    ]
