# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvayaApp', '0006_auto_20170505_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='AgeGroup',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
