# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvayaApp', '0007_auto_20170505_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='UserName',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
