# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvayaApp', '0009_auto_20170506_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Contact',
            field=models.IntegerField(null=True),
        ),
    ]
