# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvayaApp', '0010_auto_20170506_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Specialization',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
