# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvayaApp', '0012_hospital_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Gender',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
